### ISSUE TITLE
Averages mixed with individual grades

### ISSUE THREAD

**Issue by Vogeltak** [KeizerDev/Mister#14]
When a subject's average is selected the application opens a page with individual grades. On this pages are also the averages of that subject displayed. This should not be the case.
<img src="https://cloud.githubusercontent.com/assets/7063067/7233606/4b0f213e-e782-11e4-9b69-a9d5e40b9a23.png" alt="Mister Cijfers" width="350px">

**Comment by KeizerDev** [comment]
I'm going to fix this later this week!

**Comment by KeizerDev** [comment]
Fixed in one of the updates
