### ISSUE TITLE
Homework is not viewable on start page

### ISSUE THREAD

**Issue by Vogeltak** [KeizerDev/Mister#15]
On the page opened on startup your schedule for the day is displayed. The pencils indicating a homework assignment are also visible. Though the homework description won't expand like in your agenda when the subject is clicked.

**Comment by KeizerDev** [comment]
It wasn't meant like that... It is like in the Meta app you can only see that you have homework not what... Do you want to see it right away?

**Comment by Vogeltak** [comment]
If the user clicks the subject I think it should show the homework if applicable. It eliminates the step of going to your agenda to view your homework for today. Efficiency! :)

**Comment by KeizerDev** [comment]
True, I'll add it to the next version!

**Comment by KeizerDev** [comment]
Fixed in v1.01
