### ISSUE TITLE
Where is the source code?

### ISSUE THREAD

**Issue by Vogeltak** [KeizerDev/Mister#2]
There are better ways to distribute builds than via Github. It would be more logical if you share the source code of your application here.

**Comment by lieuwex** [comment]
+1 for source code :D

**Comment by KeizerDev** [comment]
Sorry, not for now... When I release it in the google play market it will be.
Thanks for your interest!

**Comment by Vogeltak** [comment]
Will you release it under a free software license? (something like GPL3 or Apache?) Then you may want to submit it for inclusion in the [f-droid repository](https://f-droid.org/wiki/page/Inclusion_Policy) too.

**Comment by KeizerDev** [comment]
I will look for it when I've finished my app!

**Comment by KeizerDev** [comment]
Sorry guys, I've decided to keep this project as a closed source project for now, but I want to give you guys a way to contribute to the project by doing some little(or big) things, like typo checking and designing, my weak point, and if you have something I have to add or some cool feature, let me know, I'll add it for sure!
Sorry if you were interested in the source code...
I would like to see you guys contributing in any way, I appreciate every little message.
