### ISSUE TITLE
Best way to notify app users when there is a new build available without custom code

### ISSUE THREAD

**Issue by KeizerDev** [KeizerDev/Mister#3]
Hi,

I just wanted to ask you guys what the best way is for you to get notified when there is a new build available, any tips?

**Comment by lieuwex** [comment]
- Using Google Play
- Using GitHub releases

**Comment by KeizerDev** [comment]
I'm not planning to release it in the Market while I'm in beta and I'll take a look at Github releases.
Thanks!

**Comment by Vogeltak** [comment]
Here is a developer.android.com article about alternative ways of distribution http://developer.android.com/distribute/tools/open-distribution.html

**Comment by KeizerDev** [comment]
Thanks, but I'll fix some bugs and then I will put it on the market! I'm planning to release it in less then a week! Thanks!

**Comment by Vogeltak** [comment]
Great!  By the way, are some things in the menu not implemented yet? I can't view the `Cijfers` tab for example. Neither are there any settings to be messed with. Just my face shows up.

Also, it would be helpful if you implement back buttons, they are quite handy to have.

**Comment by KeizerDev** [comment]
True, I've to implement `Cijfers` and add some reload buttons on every fragment instead of the settings button.  
If you have downloaded the newest build you will be see that there is a setting in the settingsfragment but it still does nothing.
I'm busy adding everything. Do you have any idea what I can add more to the settings?
You can add it to the strings.xml.  

That's weird. Do you mean back buttons on the actionbar(toolbar) or on-phone back button (that should work I think)?

**Comment by KeizerDev** [comment]
_bump_

**Comment by Vogeltak** [comment]
Maybe you can add some stuff from /api/account in settings, as information about the student.
On-phone back buttons work fine, but not having an in application back button is quite annoying. So my suggestion is to add a back button in the actionbar.

**Comment by tkon99** [comment]
+1

**Comment by KeizerDev** [comment]
I will do, thanks!

**Comment by KeizerDev** [comment]
Things to add like, on screen back buttons and more information in the settings can be added to the [TODO.md](https://github.com/KeizerDev/Mister/blob/master/TODO.md) file.

**Comment by KeizerDev** [comment]
I've updated the [README.md](https://github.com/KeizerDev/Mister/blob/master/README.md). The new way of testing the app is just using Google Play. You now can sign up to become a beta tester of my app.

**Comment by KeizerDev** [comment]
EDIT: If you want to have the updates from the play store you'll have to remove the old version(you've installed using an .apk file) first.

**Comment by KeizerDev** [comment]
EDIT: Today I've published the app in the Google Play Store! Everybody should be able to download it within a hour!
Would be cool if we can reach as many users as possible, so don't hesitate to promote the app in any way!  
You can download it by searching for "Mister" or by this link https://play.google.com/store/apps/details?id=nl.mister

**Comment by Vogeltak** [comment]
Hehe that typo finally bothered you enough to change it. Then you closed the issues...

**Comment by KeizerDev** [comment]
Haha, that stupid typo...
