### ISSUE TITLE
Absentie permissions

### ISSUE THREAD

**Issue by Vogeltak** [KeizerDev/Mister#4]
You have implemented an `Absentie` page in your app, but permissions for viewing a student's absence are not always given to students. My school for example does not give students permission to view their absence. I suggest you implement a check for permissions under the Absentie tab and inform the user about the results.
This is what my permissions for `Absentie` look like: 

```
{
    "Naam": "Absenties",
    "AccessType": ["None"]
},
```

**Comment by KeizerDev** [comment]
Thanks for notice, in the new build I will do a check when you log in and then check your permissions!
Is there something you would like to see instead of absentie?

**Comment by KeizerDev** [comment]
Fixed in 9597a33ec525aedad0f58bc885977337cc6491f7
