### ISSUE TITLE
Icons in menu are too big

### ISSUE THREAD

**Issue by Vogeltak** [KeizerDev/Mister#5]
This may be very personal, but the icons are way too big for my liking.

**Comment by KeizerDev** [comment]
Weird, what is your screen dpi? The ImageView is 40dp by 40dp so I think you're phone has a low dpi I think? Can I have a screenshot or some more info about your phone?

**Comment by KeizerDev** [comment]
Wait, do you think they are to big in my screenshot too?

**Comment by Vogeltak** [comment]
Sorry I didn't clarify enough. I also find them too big in your screenshots. Not just something on my device. (Moto g 2014 btw)

**Comment by KeizerDev** [comment]
If you look to the [Meta app](https://play.google.com/store/apps/details?id=nl.schoolmaster.meta&hl=nl_NL) I think those are fine except for the settings icon, that icon is to big I think.
I think I'm not gonna change the layout till I've found someone who can design and makes a better layout. Do you happen to know someone who can do that?

**Comment by Vogeltak** [comment]
Do what exactly? Design completely new icons? I think the application currently looks pretty slick, well, apart fromt the icons then :P
By the way, I don't think the Meta application is a good example of how applications should be nowadays. Haha, it's pretty horrific.

**Comment by KeizerDev** [comment]
No, just redesign the app for a bit. I've build it out of my fantasy without any designs or something and except for the login fragments It is still not beautiful... I was hoping to get someone who can redesign some fragments and just show me how it have to look. And I totally agree that Meta is pretty horrific haha. That's also the reason why I've started building this ;P

**Comment by Vogeltak** [comment]
Well, the android developer website always is a pretty good resource. Have a look at these pages:
- https://developer.android.com/design/material/index.html
- https://developer.android.com/training/material/index.html

These should provide you with a pretty good basis for your design.
Which version of android do you currently use?

**Comment by KeizerDev** [comment]
Yes of course, I'm using the toolbar, the color palette, the icons and quiet some other things as you can see but for the Mister app I had to make some custom views too, like the dayselector and the menu. I'm not a good designer or something and wanted some designs from anybody who likes to do that.
I'm currently testing on a: 
- Samsung galaxy S4 (Updated yesterday from 4.4 to 5.0.1 (I will update the screenshots in a minute))
- Samsung galaxy Tab 2 (4.2.2)
- Samsung galaxy ace (2.3)  

And sometimes on the HTC M8 and the Google nexus 5. 
So I have a lot of different android versions I can test on.

**Comment by Vogeltak** [comment]
Well, I may be somewhat of a designer, but my Android skills are not very good yet. Just started looking into development again. 
Those are a lot of devices you can test on, great! Sadly I am the only one with an Android device in my household so my testing devices are not that plentiful. Currently only using the Moto G 2014 with Android 5.0.2.

**Comment by KeizerDev** [comment]
Oh cool, can you just make something of how you want to see the menu, then I will think about it and change it. The icons can you find in the design folder.
I'm the only Android user too, just Apple fans everywhere... :p 
But that's cool, in what languages can you code?

**Comment by Vogeltak** [comment]
The menu design of the Google apps is really cool. Just open up a _Play .._ app like _Play Books_ and get inspired by the menu.

I have spent most of my time with front end web development. It is just so easy to make stuff, you keep making more stuff. Lately I have been working with some PHP too, it's not a very pretty language but again, it is super duper easy to make stuff. I have also played around with (in order of fluency) Java, Python and C. I probably forgot a few things, but that is not really of any importance then.

What about you?

**Comment by tkon99** [comment]
@KeizerDev Do you have a consistent design strategy? Your app looks great but it's a little "off" material. Perhaps make it look more like Play Books (like @Vogeltak suggested).

**Comment by KeizerDev** [comment]
@tkon99 Ok, thanks! I will take a look at it but I'm not a fan of the material menu in this kind of project. I don't think it belong to the Mister app because it must be easy to use and just wysiwyg, no more or less. I've decide to do it a bit "off" material.

@Vogeltak, I have spent most of my time with front- and backend development too. I'm now working as a front- and backend developer(with Drupal) in my holidays and since the last two years I'm doing some Java, Nodejs, Python and that kind of stuff... Therefor I've done a little bit of C# and C++, I'm not a pro in that...
