### ISSUE TITLE
Settings title is description

### ISSUE THREAD

**Issue by Vogeltak** [KeizerDev/Mister#6]
The setting to log out has its description as its title. This should probably not be the case.
Here's a picture:
<img src="https://cloud.githubusercontent.com/assets/7063067/6982751/2c667e86-da16-11e4-8725-537015b2f107.png" width="256px">

**Comment by KeizerDev** [comment]
Yeah, I noticed it. It was `getString(R.string.settings_loguit_description)` instead of `getString(R.string.settings_loguit)`... I'll fix it in the new build.

**Comment by Vogeltak** [comment]
Great!

**Comment by KeizerDev** [comment]
Fixed in last commit 4dd087c294e225f6f71f234da23c58116a2b21ce
